### ISSUE TITLE
ember-orbit not present in npm?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [orbitjs/ember-orbit#135]
Today I was trying ember-orbit and got this:

```
┌─[julian-acosta][MacBook-Air-de-Julian][±][master ✓][~/dev/ember-orbit-test]
└─▪ ember install ember-orbit
Registry returned 404 for GET on https://registry.npmjs.org/ember-orbit
Error: Registry returned 404 for GET on https://registry.npmjs.org/ember-orbit
    at makeError (/Users/julian-acosta/dev/ember-orbit-test/node_modules/ember-cli/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
    at CachingRegistryClient.<anonymous> (/Users/julian-acosta/dev/ember-orbit-test/node_modules/ember-cli/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
    at Request._callback (/Users/julian-acosta/dev/ember-orbit-test/node_modules/ember-cli/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
    at Request.self.callback (/Users/julian-acosta/dev/ember-orbit-test/node_modules/ember-cli/node_modules/npm/node_modules/request/request.js:200:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/julian-acosta/dev/ember-orbit-test/node_modules/ember-cli/node_modules/npm/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/julian-acosta/dev/ember-orbit-test/node_modules/ember-cli/node_modules/npm/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

https://www.npmjs.com/search?q=ember+orbit

**Comment by dgeb** [comment]
Just published 0.9.0 to npm after a massive refactor of both orbit and ember-orbit. Sorry for the lack of response here.
